In [5]:
import numpy as np
import matplotlib.pyplot as plt
D=np.diag([1,2,3,4,5,6])
R=np.random.rand(3,4)
d=np.diag(R)
print(D)
print("This one matrix")
print(R)


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
This one matrix
[[0.54608395 0.63000456 0.11819394 0.52095818]
 [0.64628936 0.99392889 0.04497874 0.28240913]
 [0.7910304  0.69054931 0.14807728 0.9393756 ]]
