In [8]:
import numpy as np
import matplotlib.pyplot as plt
M1=np.random.randn(5,3)
M2=np.random.randn(3,2)
C = M1 @ M2
print("This is M1 Matrix")
print(M1)
print("This is M2 Matrix")
print(M2)
print("M1  x  M2 =  ")
print(C)


[[ 0.15380449  0.21196922 -0.7465356 ]
 [ 0.28559495 -0.43733672  0.01964346]
 [ 1.09356677  1.98556675 -1.40240458]
 [-0.9903295  -0.40716312 -1.79922233]
 [ 1.05956487  0.7492558   1.37451086]]
[[1.30910939 0.9884739 ]
 [0.64631174 3.06835666]
 [0.86576224 1.52278511]]
M1  x  M2 =  
[[-0.30797724 -0.3343844 ]
 [ 0.10822574 -1.02968912]
 [ 1.5007447   5.03782839]
 [-3.11730269 -4.96806548]
 [ 3.06133875  5.43942093]]
