In [1]:
import numpy as np
import matplotlib.pyplot as plt
v1=[1,2,3,4]
v2=np.array([2,3,4])
v3=np.array([[1],[2],[3],[4]])
v4=np.array([[5,6,7,8,9]])
print("this is first vector")
print(v1)
print("this is second vector")
print(v2)
print("this is third vector")
print(v3)
print("this is fourth vector ")
print(v4)

this is first vector
[1, 2, 3, 4]
this is second vector
[2 3 4]
this is third vector
[[1]
 [2]
 [3]
 [4]]
this is fourth vector 
[[5 6 7 8 9]]
