In [2]:
import  numpy as np
import matplotlib.pyplot as plt
I=np.eye(5)
O=np.ones(5)
Z=np.zeros((5,5))
print("This is the Identity vector")
print(I)
print("This is Ones vector")
print(O)
print("This is Zero vector ")
print(Z)

This is the Identity vector
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
This is Ones vector
[1. 1. 1. 1. 1.]
This is Zero vector 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
